testing full

diff --git a/.github/workflows/TomcatIntegrationTest.yml b/.github/workflows/TomcatIntegrationTest.yml
--- a/.github/workflows/TomcatIntegrationTest.yml
+++ b/.github/workflows/TomcatIntegrationTest.yml
@@ -47,10 +47,10 @@ jobs:
           run: mvn -B test -q --file tomcat/pom.xml
 
         - name: Get webapps
-          if: ${{ failure() }}
+          #if: ${{ failure() }}
           run: |
             kubectl get tomcats,webapps -A -o yaml | tee -a debug
-            kubectl logs 
+            kubectl -n tomcat-test -c tomcat logs -l app=test-tomcat1 | grep startup
 
     tomcat_local_apply_setup_test:
        runs-on: ubuntu-latest
@@ -182,5 +182,27 @@ jobs:
               echo "loop number $LOOP" &&\
               sleep 5; \
             done
+            #Waiting 5 seconds for Tomcat to unpack the downloaded war
+            sleep 5;
 
+        - name: Get webapps
+          #if: ${{ failure() }}
+          run: |
+            kubectl get tomcats,webapps -A -o yaml | tee -a debug
+            kubectl -n tomcat-test -c tomcat logs -l app=test-tomcat1 | grep startup 
         
+        - name: check code
+          run: |
+              kubectl -n tomcatoperator-sample run sample1 --labels=app=curl --image=curlimages/curl:7.78.0   --restart=Never --timeout=30s --command -- curl -s -v http://test-tomcat1/mysample/;
+              kubectl -n tomcatoperator-sample run sample2 --labels=app=curl --image=curlimages/curl:7.78.0   --restart=Never --timeout=30s --command -- curl -s -v http://test-tomcat2/othercontext/;
+              LOOP=0 &&\
+              while [[ $(kubectl get pods -n tomcatoperator-sample -l app=curl -o 'jsonpath={..status.phase}') != "Succeeded Succeeded" ]]; do \
+                echo "waiting for pod" &&\
+                kubectl logs -n tomcatoperator-sample -l app=curl &&\
+                (( LOOP++ )) &&\
+                if [[ $LOOP -gt 5 ]]; then exit 1; fi &&\
+                echo "loop number $LOOP" &&\
+                sleep 5; \
+              done
+              if [[ $(kubectl logs -n tomcatoperator-sample sample1 --tail=500 | grep tomcat.gif | wc -l) -ne 1 ]]; then exit 1; fi
+              if [[ $(kubectl logs -n tomcatoperator-sample sample2 --tail=500 | grep dog.jpeg | wc -l) -ne 1 ]]; then exit 1; fi
